services:
  api:
    container_name: debug_test_api
    image: node:12.18.4
    volumes:
        - type: bind
          source: ./api
          target: /code
    working_dir: /code
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=librarypass
      - PGDATABASE=library_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: debug_test_db
    image: postgres:12.4
    volumes:
      - "test_db:/var/lib/postgresql/data"           
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=library_test
      - POSTGRES_PASSWORD=librarypass
      - POSTGRES_USER=futureproof
volumes:
  test_db:
networks: 
  default:
    name: debug_test
