version: '3.2'
services:
    client:
        container_name: dev-client
        image: node:12.18.4
        ports: 
          - 8080:8080
        volumes:
          - type: bind
            source: ./client
            target: /code
        working_dir: /code
        command: bash -c "npm install && npm run dev"
    api:
        container_name: dev-server
        image: node:12.18.4
        volumes:
            - type: bind
              source: ./api
              target: /code
        working_dir: /code
        ports: 
          - 5000:5000
        environment: 
          - PGUSER=naans
          - PGHOST=db
          - PGPASSWORD=stocks123
          - PGDATABASE=portfolio
          - PGPORT=5432
          - NODE_ENV=development
        depends_on:
          - db
        command: bash -c "npm install && npm run seedDev && npm run dev"
    
    db:
        container_name: dev-db
        image: postgres:12.4
        volumes:
          - "dbdata:/var/lib/postgresql/data"          
          - "./db:/docker-entrypoint-initdb.d/:ro"
        environment: 
            - POSTGRES_PASSWORD=stocks123
            - POSTGRES_USER=naans
            - POSTGRES_DB=portfolio
volumes:
    dbdata:

        